// AUTO-GENERATED by tools/audio-lab/render.mjs. Do not edit by hand; re-run the render instead.
// All positions are in samples at AUDIO_SR (convert to seconds at runtime).

export const AUDIO_VERSION = 'd70ce823';
export const AUDIO_SR = 44100;

export type BankId = 'core' | 'extra';
export interface BankInfo { file: string; samples: number }
export interface SoundInfo { bank: BankId; start: number; length: number; loopStart?: number; loopEnd?: number }
/** nums[i] is the index value variant ids[i] answers to (steps may be non-contiguous, e.g. boost 2,3,4,5,7,10,15,20). */
export interface VariantInfo { base: number; nums: number[]; ids: string[] }
export interface TrackInfo {
  file: string; samples: number; loopStart: number; loopEnd: number;
  bpm: number; beatsPerBar: number; bars: number; stems: Record<string, string>;
}

export const BANKS: Partial<Record<BankId, BankInfo>> = {
  "core": {
    "file": "sfx-core.mp3",
    "samples": 6508418
  },
  "extra": {
    "file": "sfx-extra.mp3",
    "samples": 1382463
  }
};

export const SOUNDS: Record<string, SoundInfo> = {
  "uiClick": {
    "bank": "core",
    "start": 2205,
    "length": 8046
  },
  "uiToggle": {
    "bank": "core",
    "start": 12897,
    "length": 10455
  },
  "uiOpen": {
    "bank": "core",
    "start": 25998,
    "length": 23832
  },
  "uiClose": {
    "bank": "core",
    "start": 52476,
    "length": 14147
  },
  "betUp": {
    "bank": "core",
    "start": 69269,
    "length": 20677
  },
  "betDown": {
    "bank": "core",
    "start": 92592,
    "length": 22961
  },
  "spinPress": {
    "bank": "core",
    "start": 118199,
    "length": 13390
  },
  "buy": {
    "bank": "core",
    "start": 134235,
    "length": 43908
  },
  "error": {
    "bank": "core",
    "start": 180789,
    "length": 30866
  },
  "iris": {
    "bank": "core",
    "start": 214301,
    "length": 47246
  },
  "boostOn": {
    "bank": "core",
    "start": 264193,
    "length": 26714
  },
  "boostOff": {
    "bank": "core",
    "start": 293553,
    "length": 21401
  },
  "lowPowerClick": {
    "bank": "core",
    "start": 317600,
    "length": 7740
  },
  "reelDrop_0": {
    "bank": "core",
    "start": 327986,
    "length": 10338
  },
  "reelDrop_1": {
    "bank": "core",
    "start": 340970,
    "length": 13017
  },
  "reelDrop_2": {
    "bank": "core",
    "start": 356633,
    "length": 10826
  },
  "reelDrop_3": {
    "bank": "core",
    "start": 370105,
    "length": 11223
  },
  "reelDrop_4": {
    "bank": "core",
    "start": 383974,
    "length": 10799
  },
  "reelStop": {
    "bank": "core",
    "start": 397419,
    "length": 26163
  },
  "symbolFall_0": {
    "bank": "core",
    "start": 426228,
    "length": 13770
  },
  "symbolFall_1": {
    "bank": "core",
    "start": 442644,
    "length": 14629
  },
  "symbolFall_2": {
    "bank": "core",
    "start": 459919,
    "length": 15427
  },
  "cascade_0": {
    "bank": "core",
    "start": 477992,
    "length": 17102
  },
  "cascade_1": {
    "bank": "core",
    "start": 497740,
    "length": 16301
  },
  "pop_0": {
    "bank": "core",
    "start": 516687,
    "length": 11512
  },
  "pop_1": {
    "bank": "core",
    "start": 530845,
    "length": 11090
  },
  "pop_2": {
    "bank": "core",
    "start": 544581,
    "length": 11362
  },
  "sixLand": {
    "bank": "core",
    "start": 558589,
    "length": 34662
  },
  "sixIgnite": {
    "bank": "core",
    "start": 595897,
    "length": 70560
  },
  "fsLand_1": {
    "bank": "core",
    "start": 669103,
    "length": 44382
  },
  "fsLand_2": {
    "bank": "core",
    "start": 716131,
    "length": 42965
  },
  "fsLand_3": {
    "bank": "core",
    "start": 761742,
    "length": 47900
  },
  "fsLand_4": {
    "bank": "core",
    "start": 812288,
    "length": 49619
  },
  "fsLand_5": {
    "bank": "core",
    "start": 864553,
    "length": 53266
  },
  "fsLand_6": {
    "bank": "core",
    "start": 920465,
    "length": 71768
  },
  "win_0": {
    "bank": "core",
    "start": 994879,
    "length": 42410
  },
  "win_1": {
    "bank": "core",
    "start": 1039935,
    "length": 43574
  },
  "win_2": {
    "bank": "core",
    "start": 1086155,
    "length": 41778
  },
  "win_3": {
    "bank": "core",
    "start": 1130579,
    "length": 43300
  },
  "win_4": {
    "bank": "core",
    "start": 1176525,
    "length": 44785
  },
  "win_5": {
    "bank": "core",
    "start": 1223956,
    "length": 42717
  },
  "win_6": {
    "bank": "core",
    "start": 1269319,
    "length": 43913
  },
  "win_7": {
    "bank": "core",
    "start": 1315878,
    "length": 43793
  },
  "coin_0": {
    "bank": "core",
    "start": 1362317,
    "length": 12142
  },
  "coin_1": {
    "bank": "core",
    "start": 1377105,
    "length": 14382
  },
  "coin_2": {
    "bank": "core",
    "start": 1394133,
    "length": 14026
  },
  "coin_3": {
    "bank": "core",
    "start": 1410805,
    "length": 16519
  },
  "coin_4": {
    "bank": "core",
    "start": 1429970,
    "length": 13619
  },
  "coin_5": {
    "bank": "core",
    "start": 1446235,
    "length": 12847
  },
  "coin_6": {
    "bank": "core",
    "start": 1461728,
    "length": 15018
  },
  "coin_7": {
    "bank": "core",
    "start": 1479392,
    "length": 16408
  },
  "cashBronze": {
    "bank": "core",
    "start": 1498446,
    "length": 28906
  },
  "cashSilver": {
    "bank": "core",
    "start": 1529998,
    "length": 48868
  },
  "cashGold": {
    "bank": "core",
    "start": 1581512,
    "length": 83374
  },
  "multAdd": {
    "bank": "core",
    "start": 1667532,
    "length": 66004
  },
  "wheelAppear": {
    "bank": "core",
    "start": 1736182,
    "length": 45526
  },
  "wheelSpin": {
    "bank": "core",
    "start": 1784354,
    "length": 54684,
    "loopStart": 1789646,
    "loopEnd": 1833746
  },
  "wheelTick_0": {
    "bank": "core",
    "start": 1841684,
    "length": 6490
  },
  "wheelTick_1": {
    "bank": "core",
    "start": 1850820,
    "length": 6615
  },
  "wheelTick_2": {
    "bank": "core",
    "start": 1860081,
    "length": 6615
  },
  "wheelTick_3": {
    "bank": "core",
    "start": 1869342,
    "length": 6615
  },
  "wheelLand": {
    "bank": "core",
    "start": 1878603,
    "length": 60253
  },
  "howl": {
    "bank": "core",
    "start": 1941502,
    "length": 69948
  },
  "multMul": {
    "bank": "core",
    "start": 2014096,
    "length": 96554
  },
  "wheelPullback": {
    "bank": "core",
    "start": 2113296,
    "length": 27644
  },
  "wheelLandClunk": {
    "bank": "core",
    "start": 2143586,
    "length": 25976
  },
  "wheelIconLift": {
    "bank": "core",
    "start": 2172208,
    "length": 61452
  },
  "wheelBombReveal": {
    "bank": "core",
    "start": 2236306,
    "length": 84127
  },
  "barTick_0": {
    "bank": "core",
    "start": 2323079,
    "length": 1323
  },
  "barTick_1": {
    "bank": "core",
    "start": 2327048,
    "length": 1323
  },
  "barTick_2": {
    "bank": "core",
    "start": 2331017,
    "length": 1323
  },
  "barApply": {
    "bank": "core",
    "start": 2334986,
    "length": 49505
  },
  "bonusTrigger": {
    "bank": "core",
    "start": 2387137,
    "length": 92802
  },
  "sealStamp": {
    "bank": "core",
    "start": 2482585,
    "length": 24957
  },
  "clusterTrace": {
    "bank": "core",
    "start": 2510188,
    "length": 50801
  },
  "anticipationStart": {
    "bank": "core",
    "start": 2563635,
    "length": 68715
  },
  "anticipationEnd": {
    "bank": "core",
    "start": 2634996,
    "length": 38932
  },
  "anticipation": {
    "bank": "core",
    "start": 2676574,
    "length": 222264,
    "loopStart": 2681866,
    "loopEnd": 2893546
  },
  "explode_1": {
    "bank": "core",
    "start": 2901484,
    "length": 31835
  },
  "explode_2": {
    "bank": "core",
    "start": 2935965,
    "length": 29355
  },
  "explode_3": {
    "bank": "core",
    "start": 2967966,
    "length": 31409
  },
  "explode_4": {
    "bank": "core",
    "start": 3002021,
    "length": 32114
  },
  "explode_5": {
    "bank": "core",
    "start": 3036781,
    "length": 32802
  },
  "explode_6": {
    "bank": "core",
    "start": 3072229,
    "length": 32175
  },
  "blastDebris_0": {
    "bank": "core",
    "start": 3107050,
    "length": 12657
  },
  "blastDebris_1": {
    "bank": "core",
    "start": 3122353,
    "length": 13263
  },
  "blastDebris_2": {
    "bank": "core",
    "start": 3138262,
    "length": 11065
  },
  "blastDebris_3": {
    "bank": "core",
    "start": 3151973,
    "length": 12753
  },
  "meterFlame_1": {
    "bank": "core",
    "start": 3167372,
    "length": 12965
  },
  "meterFlame_2": {
    "bank": "core",
    "start": 3182983,
    "length": 12454
  },
  "meterFlame_3": {
    "bank": "core",
    "start": 3198083,
    "length": 13209
  },
  "meterFlame_4": {
    "bank": "core",
    "start": 3213938,
    "length": 13104
  },
  "meterFlame_5": {
    "bank": "core",
    "start": 3229688,
    "length": 13034
  },
  "meterFlame_6": {
    "bank": "core",
    "start": 3245368,
    "length": 13057
  },
  "meterFlame_7": {
    "bank": "core",
    "start": 3261071,
    "length": 13541
  },
  "meterFlame_8": {
    "bank": "core",
    "start": 3277258,
    "length": 13947
  },
  "meterFlame_9": {
    "bank": "core",
    "start": 3293851,
    "length": 13313
  },
  "meterFlame_10": {
    "bank": "core",
    "start": 3309810,
    "length": 13805
  },
  "meterFull": {
    "bank": "core",
    "start": 3326261,
    "length": 105703
  },
  "hounds_1": {
    "bank": "core",
    "start": 3434610,
    "length": 34038
  },
  "hounds_2": {
    "bank": "core",
    "start": 3471294,
    "length": 35974
  },
  "hounds_3": {
    "bank": "core",
    "start": 3509914,
    "length": 40737
  },
  "hounds_4": {
    "bank": "core",
    "start": 3553297,
    "length": 46741
  },
  "hounds_5": {
    "bank": "core",
    "start": 3602684,
    "length": 51527
  },
  "inferno": {
    "bank": "core",
    "start": 3656857,
    "length": 65911
  },
  "boost_2": {
    "bank": "core",
    "start": 3725414,
    "length": 61739
  },
  "boost_3": {
    "bank": "core",
    "start": 3789799,
    "length": 61739
  },
  "boost_4": {
    "bank": "core",
    "start": 3854184,
    "length": 61739
  },
  "boost_5": {
    "bank": "core",
    "start": 3918569,
    "length": 61739
  },
  "boost_7": {
    "bank": "core",
    "start": 3982954,
    "length": 61739
  },
  "boost_10": {
    "bank": "core",
    "start": 4047339,
    "length": 61739
  },
  "boost_15": {
    "bank": "core",
    "start": 4111724,
    "length": 61739
  },
  "boost_20": {
    "bank": "core",
    "start": 4176109,
    "length": 61739
  },
  "wildLand_0": {
    "bank": "core",
    "start": 4240494,
    "length": 31770
  },
  "wildLand_1": {
    "bank": "core",
    "start": 4274910,
    "length": 31370
  },
  "wildLand_2": {
    "bank": "core",
    "start": 4308926,
    "length": 30575
  },
  "bombLand": {
    "bank": "core",
    "start": 4342147,
    "length": 29434
  },
  "bombFuseLoop": {
    "bank": "core",
    "start": 4374227,
    "length": 142884,
    "loopStart": 4379519,
    "loopEnd": 4511819
  },
  "bombTick": {
    "bank": "core",
    "start": 4519757,
    "length": 11390
  },
  "bombHotLoop": {
    "bank": "core",
    "start": 4533793,
    "length": 151704,
    "loopStart": 4539085,
    "loopEnd": 4680205
  },
  "bombGrow_1": {
    "bank": "core",
    "start": 4688143,
    "length": 46041
  },
  "bombGrow_2": {
    "bank": "core",
    "start": 4736830,
    "length": 46315
  },
  "bombGrow_3": {
    "bank": "core",
    "start": 4785791,
    "length": 47080
  },
  "bombGrow_4": {
    "bank": "core",
    "start": 4835517,
    "length": 46037
  },
  "bombGrow_5": {
    "bank": "core",
    "start": 4884200,
    "length": 47630
  },
  "bombBlast_1": {
    "bank": "core",
    "start": 4934476,
    "length": 40599
  },
  "bombBlast_2": {
    "bank": "core",
    "start": 4977721,
    "length": 57008
  },
  "bombBlast_3": {
    "bank": "core",
    "start": 5037375,
    "length": 91527
  },
  "bombBlast_4": {
    "bank": "core",
    "start": 5131548,
    "length": 115201
  },
  "bombBlast_5": {
    "bank": "core",
    "start": 5249395,
    "length": 134771
  },
  "bombChain_0": {
    "bank": "core",
    "start": 5386812,
    "length": 44973
  },
  "bombChain_1": {
    "bank": "core",
    "start": 5434431,
    "length": 44890
  },
  "bombChain_2": {
    "bank": "core",
    "start": 5481967,
    "length": 44781
  },
  "endRumble": {
    "bank": "core",
    "start": 5529394,
    "length": 101826
  },
  "capBelt": {
    "bank": "core",
    "start": 5633866,
    "length": 20971
  },
  "capChargePip_1": {
    "bank": "core",
    "start": 5657483,
    "length": 39306
  },
  "capChargePip_2": {
    "bank": "core",
    "start": 5699435,
    "length": 39574
  },
  "capChargePip_3": {
    "bank": "core",
    "start": 5741655,
    "length": 39622
  },
  "capChargeFull": {
    "bank": "core",
    "start": 5783923,
    "length": 70426
  },
  "capWindup": {
    "bank": "core",
    "start": 5856995,
    "length": 52868
  },
  "capThrow": {
    "bank": "core",
    "start": 5912509,
    "length": 36910
  },
  "capPegTap_0": {
    "bank": "core",
    "start": 5952065,
    "length": 8801
  },
  "capPegTap_1": {
    "bank": "core",
    "start": 5963512,
    "length": 9433
  },
  "capPegTap_2": {
    "bank": "core",
    "start": 5975591,
    "length": 9319
  },
  "parrotSquawk": {
    "bank": "core",
    "start": 5987556,
    "length": 43743
  },
  "parrotFlap_0": {
    "bank": "core",
    "start": 6033945,
    "length": 16291
  },
  "parrotFlap_1": {
    "bank": "core",
    "start": 6052882,
    "length": 19597
  },
  "symCrab": {
    "bank": "core",
    "start": 6075125,
    "length": 8963
  },
  "symOcto": {
    "bank": "core",
    "start": 6086734,
    "length": 12436
  },
  "symShark": {
    "bank": "core",
    "start": 6101816,
    "length": 9028
  },
  "symParrot": {
    "bank": "core",
    "start": 6113490,
    "length": 16291
  },
  "symAnchor": {
    "bank": "core",
    "start": 6132427,
    "length": 29170
  },
  "symShell": {
    "bank": "core",
    "start": 6164243,
    "length": 29975
  },
  "symMap": {
    "bank": "core",
    "start": 6196864,
    "length": 34970
  },
  "symCompass": {
    "bank": "core",
    "start": 6234480,
    "length": 25050
  },
  "introSting": {
    "bank": "core",
    "start": 6262176,
    "length": 123567
  },
  "playSting": {
    "bank": "core",
    "start": 6388389,
    "length": 75378
  },
  "carouselWhoosh": {
    "bank": "core",
    "start": 6466413,
    "length": 17264
  },
  "coachPop": {
    "bank": "core",
    "start": 6486323,
    "length": 17244
  },
  "bonusIntro": {
    "bank": "extra",
    "start": 2205,
    "length": 132234
  },
  "bonusEnd": {
    "bank": "extra",
    "start": 137085,
    "length": 148414
  },
  "retrigger": {
    "bank": "extra",
    "start": 288145,
    "length": 85865
  },
  "bigWinStart": {
    "bank": "extra",
    "start": 376656,
    "length": 113405
  },
  "bigWinTier_0": {
    "bank": "extra",
    "start": 492707,
    "length": 105840
  },
  "bigWinTier_1": {
    "bank": "extra",
    "start": 601193,
    "length": 105519
  },
  "bigWinTier_2": {
    "bank": "extra",
    "start": 709358,
    "length": 105840
  },
  "bigWinTier_3": {
    "bank": "extra",
    "start": 817844,
    "length": 103081
  },
  "bigWinEnd": {
    "bank": "extra",
    "start": 923571,
    "length": 145255
  },
  "maxWin": {
    "bank": "extra",
    "start": 1071472,
    "length": 220116
  },
  "tierSlam": {
    "bank": "extra",
    "start": 1294234,
    "length": 83378
  }
};

export const VARIANTS: Record<string, VariantInfo> = {
  "uiClick": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiClick"
    ]
  },
  "uiToggle": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiToggle"
    ]
  },
  "uiOpen": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiOpen"
    ]
  },
  "uiClose": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiClose"
    ]
  },
  "betUp": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "betUp"
    ]
  },
  "betDown": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "betDown"
    ]
  },
  "spinPress": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "spinPress"
    ]
  },
  "buy": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "buy"
    ]
  },
  "error": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "error"
    ]
  },
  "iris": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "iris"
    ]
  },
  "boostOn": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "boostOn"
    ]
  },
  "boostOff": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "boostOff"
    ]
  },
  "lowPowerClick": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "lowPowerClick"
    ]
  },
  "reelDrop": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3,
      4
    ],
    "ids": [
      "reelDrop_0",
      "reelDrop_1",
      "reelDrop_2",
      "reelDrop_3",
      "reelDrop_4"
    ]
  },
  "reelStop": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "reelStop"
    ]
  },
  "symbolFall": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "symbolFall_0",
      "symbolFall_1",
      "symbolFall_2"
    ]
  },
  "cascade": {
    "base": 0,
    "nums": [
      0,
      1
    ],
    "ids": [
      "cascade_0",
      "cascade_1"
    ]
  },
  "pop": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "pop_0",
      "pop_1",
      "pop_2"
    ]
  },
  "sixLand": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "sixLand"
    ]
  },
  "sixIgnite": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "sixIgnite"
    ]
  },
  "fsLand": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "ids": [
      "fsLand_1",
      "fsLand_2",
      "fsLand_3",
      "fsLand_4",
      "fsLand_5",
      "fsLand_6"
    ]
  },
  "win": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "ids": [
      "win_0",
      "win_1",
      "win_2",
      "win_3",
      "win_4",
      "win_5",
      "win_6",
      "win_7"
    ]
  },
  "coin": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3,
      4,
      5,
      6,
      7
    ],
    "ids": [
      "coin_0",
      "coin_1",
      "coin_2",
      "coin_3",
      "coin_4",
      "coin_5",
      "coin_6",
      "coin_7"
    ]
  },
  "cashBronze": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "cashBronze"
    ]
  },
  "cashSilver": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "cashSilver"
    ]
  },
  "cashGold": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "cashGold"
    ]
  },
  "multAdd": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "multAdd"
    ]
  },
  "wheelAppear": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wheelAppear"
    ]
  },
  "wheelSpin": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wheelSpin"
    ]
  },
  "wheelTick": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3
    ],
    "ids": [
      "wheelTick_0",
      "wheelTick_1",
      "wheelTick_2",
      "wheelTick_3"
    ]
  },
  "wheelLand": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wheelLand"
    ]
  },
  "howl": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "howl"
    ]
  },
  "multMul": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "multMul"
    ]
  },
  "wheelPullback": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wheelPullback"
    ]
  },
  "wheelLandClunk": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wheelLandClunk"
    ]
  },
  "wheelIconLift": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wheelIconLift"
    ]
  },
  "wheelBombReveal": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wheelBombReveal"
    ]
  },
  "barTick": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "barTick_0",
      "barTick_1",
      "barTick_2"
    ]
  },
  "barApply": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "barApply"
    ]
  },
  "bonusTrigger": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bonusTrigger"
    ]
  },
  "sealStamp": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "sealStamp"
    ]
  },
  "clusterTrace": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "clusterTrace"
    ]
  },
  "anticipationStart": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "anticipationStart"
    ]
  },
  "anticipationEnd": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "anticipationEnd"
    ]
  },
  "anticipation": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "anticipation"
    ]
  },
  "explode": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "ids": [
      "explode_1",
      "explode_2",
      "explode_3",
      "explode_4",
      "explode_5",
      "explode_6"
    ]
  },
  "blastDebris": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3
    ],
    "ids": [
      "blastDebris_0",
      "blastDebris_1",
      "blastDebris_2",
      "blastDebris_3"
    ]
  },
  "meterFlame": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10
    ],
    "ids": [
      "meterFlame_1",
      "meterFlame_2",
      "meterFlame_3",
      "meterFlame_4",
      "meterFlame_5",
      "meterFlame_6",
      "meterFlame_7",
      "meterFlame_8",
      "meterFlame_9",
      "meterFlame_10"
    ]
  },
  "meterFull": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "meterFull"
    ]
  },
  "hounds": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5
    ],
    "ids": [
      "hounds_1",
      "hounds_2",
      "hounds_3",
      "hounds_4",
      "hounds_5"
    ]
  },
  "inferno": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "inferno"
    ]
  },
  "boost": {
    "base": 2,
    "nums": [
      2,
      3,
      4,
      5,
      7,
      10,
      15,
      20
    ],
    "ids": [
      "boost_2",
      "boost_3",
      "boost_4",
      "boost_5",
      "boost_7",
      "boost_10",
      "boost_15",
      "boost_20"
    ]
  },
  "wildLand": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "wildLand_0",
      "wildLand_1",
      "wildLand_2"
    ]
  },
  "bombLand": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bombLand"
    ]
  },
  "bombFuseLoop": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bombFuseLoop"
    ]
  },
  "bombTick": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bombTick"
    ]
  },
  "bombHotLoop": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bombHotLoop"
    ]
  },
  "bombGrow": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5
    ],
    "ids": [
      "bombGrow_1",
      "bombGrow_2",
      "bombGrow_3",
      "bombGrow_4",
      "bombGrow_5"
    ]
  },
  "bombBlast": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5
    ],
    "ids": [
      "bombBlast_1",
      "bombBlast_2",
      "bombBlast_3",
      "bombBlast_4",
      "bombBlast_5"
    ]
  },
  "bombChain": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "bombChain_0",
      "bombChain_1",
      "bombChain_2"
    ]
  },
  "endRumble": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "endRumble"
    ]
  },
  "capBelt": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "capBelt"
    ]
  },
  "capChargePip": {
    "base": 1,
    "nums": [
      1,
      2,
      3
    ],
    "ids": [
      "capChargePip_1",
      "capChargePip_2",
      "capChargePip_3"
    ]
  },
  "capChargeFull": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "capChargeFull"
    ]
  },
  "capWindup": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "capWindup"
    ]
  },
  "capThrow": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "capThrow"
    ]
  },
  "capPegTap": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "capPegTap_0",
      "capPegTap_1",
      "capPegTap_2"
    ]
  },
  "parrotSquawk": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "parrotSquawk"
    ]
  },
  "parrotFlap": {
    "base": 0,
    "nums": [
      0,
      1
    ],
    "ids": [
      "parrotFlap_0",
      "parrotFlap_1"
    ]
  },
  "symCrab": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symCrab"
    ]
  },
  "symOcto": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symOcto"
    ]
  },
  "symShark": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symShark"
    ]
  },
  "symParrot": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symParrot"
    ]
  },
  "symAnchor": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symAnchor"
    ]
  },
  "symShell": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symShell"
    ]
  },
  "symMap": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symMap"
    ]
  },
  "symCompass": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symCompass"
    ]
  },
  "introSting": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "introSting"
    ]
  },
  "playSting": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "playSting"
    ]
  },
  "carouselWhoosh": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "carouselWhoosh"
    ]
  },
  "coachPop": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "coachPop"
    ]
  },
  "bonusIntro": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bonusIntro"
    ]
  },
  "bonusEnd": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bonusEnd"
    ]
  },
  "retrigger": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "retrigger"
    ]
  },
  "bigWinStart": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bigWinStart"
    ]
  },
  "bigWinTier": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3
    ],
    "ids": [
      "bigWinTier_0",
      "bigWinTier_1",
      "bigWinTier_2",
      "bigWinTier_3"
    ]
  },
  "bigWinEnd": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bigWinEnd"
    ]
  },
  "maxWin": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "maxWin"
    ]
  },
  "tierSlam": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "tierSlam"
    ]
  }
};

export const TRACKS: Record<string, TrackInfo> = {
  "base": {
    "file": "music-base.mp3",
    "samples": 1786050,
    "loopStart": 11025,
    "loopEnd": 1775025,
    "bpm": 96,
    "beatsPerBar": 2,
    "bars": 32,
    "stems": {}
  },
  "tantrum": {
    "file": "music-tantrum.mp3",
    "samples": 2279970,
    "loopStart": 11025,
    "loopEnd": 2268945,
    "bpm": 150,
    "beatsPerBar": 4,
    "bars": 32,
    "stems": {}
  },
  "witching": {
    "file": "music-witching.mp3",
    "samples": 2138850,
    "loopStart": 11025,
    "loopEnd": 2127825,
    "bpm": 80,
    "beatsPerBar": 4,
    "bars": 16,
    "stems": {
      "tension": "music-witching-tension.mp3"
    }
  },
  "limbo": {
    "file": "music-limbo.mp3",
    "samples": 2138850,
    "loopStart": 11025,
    "loopEnd": 2127825,
    "bpm": 90,
    "beatsPerBar": 3,
    "bars": 24,
    "stems": {}
  },
  "bigwin": {
    "file": "music-bigwin.mp3",
    "samples": 727650,
    "loopStart": 11025,
    "loopEnd": 716625,
    "bpm": 120,
    "beatsPerBar": 4,
    "bars": 8,
    "stems": {}
  }
};
