// AUTO-GENERATED by tools/audio-lab/render.mjs. Do not edit by hand; re-run the render instead.
// All positions are in samples at AUDIO_SR (convert to seconds at runtime).

export const AUDIO_VERSION = 'c4fe0ca6';
export const AUDIO_SR = 44100;

export type BankId = 'core' | 'extra';
export interface BankInfo { file: string; samples: number }
export interface SoundInfo { bank: BankId; start: number; length: number; loopStart?: number; loopEnd?: number }
/** nums[i] is the index value variant ids[i] answers to (steps may be non-contiguous, e.g. boost 2,3,4,5,7,10,15,20). */
export interface VariantInfo { base: number; nums: number[]; ids: string[] }
export interface TrackInfo {
  file: string; samples: number; loopStart: number; loopEnd: number;
  bpm: number; beatsPerBar: number; bars: number; stems: Record<string, string>;
}

export const BANKS: Partial<Record<BankId, BankInfo>> = {
  "core": {
    "file": "sfx-core.mp3",
    "samples": 4438900
  },
  "extra": {
    "file": "sfx-extra.mp3",
    "samples": 1507697
  }
};

export const SOUNDS: Record<string, SoundInfo> = {
  "uiClick": {
    "bank": "core",
    "start": 2205,
    "length": 8278
  },
  "uiToggle": {
    "bank": "core",
    "start": 13129,
    "length": 10200
  },
  "uiOpen": {
    "bank": "core",
    "start": 25975,
    "length": 24155
  },
  "uiClose": {
    "bank": "core",
    "start": 52776,
    "length": 15453
  },
  "betUp": {
    "bank": "core",
    "start": 70875,
    "length": 26682
  },
  "betDown": {
    "bank": "core",
    "start": 100203,
    "length": 27681
  },
  "spinPress": {
    "bank": "core",
    "start": 130530,
    "length": 12789
  },
  "buy": {
    "bank": "core",
    "start": 145965,
    "length": 62109
  },
  "error": {
    "bank": "core",
    "start": 210720,
    "length": 30866
  },
  "iris": {
    "bank": "core",
    "start": 244232,
    "length": 57330
  },
  "boostOn": {
    "bank": "core",
    "start": 304208,
    "length": 34475
  },
  "boostOff": {
    "bank": "core",
    "start": 341329,
    "length": 26299
  },
  "lowPowerClick": {
    "bank": "core",
    "start": 370274,
    "length": 7740
  },
  "reelDrop_0": {
    "bank": "core",
    "start": 380660,
    "length": 10653
  },
  "reelDrop_1": {
    "bank": "core",
    "start": 393959,
    "length": 11859
  },
  "reelDrop_2": {
    "bank": "core",
    "start": 408464,
    "length": 11516
  },
  "reelDrop_3": {
    "bank": "core",
    "start": 422626,
    "length": 11684
  },
  "reelDrop_4": {
    "bank": "core",
    "start": 436956,
    "length": 9690
  },
  "reelDrop_5": {
    "bank": "core",
    "start": 449292,
    "length": 10038
  },
  "reelStop": {
    "bank": "core",
    "start": 461976,
    "length": 24441
  },
  "ticketLand_1": {
    "bank": "core",
    "start": 489063,
    "length": 54224
  },
  "ticketLand_2": {
    "bank": "core",
    "start": 545933,
    "length": 56816
  },
  "ticketLand_3": {
    "bank": "core",
    "start": 605395,
    "length": 84542
  },
  "ticketLand_4": {
    "bank": "core",
    "start": 692583,
    "length": 84542
  },
  "ticketLand_5": {
    "bank": "core",
    "start": 779771,
    "length": 84542
  },
  "ticketLand_6": {
    "bank": "core",
    "start": 866959,
    "length": 84544
  },
  "coinLand_0": {
    "bank": "core",
    "start": 954149,
    "length": 11304
  },
  "coinLand_1": {
    "bank": "core",
    "start": 968099,
    "length": 14612
  },
  "coinLand_2": {
    "bank": "core",
    "start": 985357,
    "length": 32581
  },
  "coinLand_3": {
    "bank": "core",
    "start": 1020584,
    "length": 65110
  },
  "locoLand": {
    "bank": "core",
    "start": 1088340,
    "length": 32879
  },
  "switchLand": {
    "bank": "core",
    "start": 1123865,
    "length": 12598
  },
  "wildLand_0": {
    "bank": "core",
    "start": 1139109,
    "length": 20019
  },
  "wildLand_1": {
    "bank": "core",
    "start": 1161774,
    "length": 19986
  },
  "wildLand_2": {
    "bank": "core",
    "start": 1184406,
    "length": 17496
  },
  "win": {
    "bank": "core",
    "start": 1204548,
    "length": 55415
  },
  "clusterTrace": {
    "bank": "core",
    "start": 1262609,
    "length": 47743
  },
  "symPretzel": {
    "bank": "core",
    "start": 1312998,
    "length": 14179
  },
  "symCoffee": {
    "bank": "core",
    "start": 1329823,
    "length": 30103
  },
  "symNewspaper": {
    "bank": "core",
    "start": 1362572,
    "length": 22470
  },
  "symUmbrella": {
    "bank": "core",
    "start": 1387688,
    "length": 19930
  },
  "symPigeon": {
    "bank": "core",
    "start": 1410264,
    "length": 41072
  },
  "symCat": {
    "bank": "core",
    "start": 1453982,
    "length": 29121
  },
  "symBulldog": {
    "bank": "core",
    "start": 1485749,
    "length": 28650
  },
  "symRat": {
    "bank": "core",
    "start": 1517045,
    "length": 21582
  },
  "symConductor": {
    "bank": "core",
    "start": 1541273,
    "length": 30419
  },
  "whistle": {
    "bank": "core",
    "start": 1574338,
    "length": 61739
  },
  "trainDepart": {
    "bank": "core",
    "start": 1638723,
    "length": 103819
  },
  "trainRun": {
    "bank": "core",
    "start": 1745188,
    "length": 76734,
    "loopStart": 1750480,
    "loopEnd": 1816630
  },
  "trainExit": {
    "bank": "core",
    "start": 1824568,
    "length": 83330
  },
  "trainBrake": {
    "bank": "core",
    "start": 1910544,
    "length": 92574
  },
  "coinCollect_1": {
    "bank": "core",
    "start": 2005764,
    "length": 29171
  },
  "coinCollect_2": {
    "bank": "core",
    "start": 2037581,
    "length": 30916
  },
  "coinCollect_3": {
    "bank": "core",
    "start": 2071143,
    "length": 33157
  },
  "coinCollect_4": {
    "bank": "core",
    "start": 2106946,
    "length": 32882
  },
  "coinCollect_5": {
    "bank": "core",
    "start": 2142474,
    "length": 31994
  },
  "coinCollect_6": {
    "bank": "core",
    "start": 2177114,
    "length": 34853
  },
  "coinCollect_7": {
    "bank": "core",
    "start": 2214613,
    "length": 33081
  },
  "coinCollect_8": {
    "bank": "core",
    "start": 2250340,
    "length": 33309
  },
  "coinCollect_9": {
    "bank": "core",
    "start": 2286295,
    "length": 33186
  },
  "coinCollect_10": {
    "bank": "core",
    "start": 2322127,
    "length": 32270
  },
  "coinCollect_11": {
    "bank": "core",
    "start": 2357043,
    "length": 33231
  },
  "coinCollect_12": {
    "bank": "core",
    "start": 2392920,
    "length": 32757
  },
  "switchThrow": {
    "bank": "core",
    "start": 2428323,
    "length": 35410
  },
  "branch": {
    "bank": "core",
    "start": 2466379,
    "length": 18190
  },
  "haulCount_0": {
    "bank": "core",
    "start": 2487215,
    "length": 1323
  },
  "haulCount_1": {
    "bank": "core",
    "start": 2491184,
    "length": 1323
  },
  "haulCount_2": {
    "bank": "core",
    "start": 2495153,
    "length": 1323
  },
  "haulMult": {
    "bank": "core",
    "start": 2499122,
    "length": 46026
  },
  "barTick_0": {
    "bank": "core",
    "start": 2547794,
    "length": 1323
  },
  "barTick_1": {
    "bank": "core",
    "start": 2551763,
    "length": 1323
  },
  "barTick_2": {
    "bank": "core",
    "start": 2555732,
    "length": 1323
  },
  "barApply": {
    "bank": "core",
    "start": 2559701,
    "length": 57197
  },
  "anticipationStart": {
    "bank": "core",
    "start": 2619544,
    "length": 77678
  },
  "anticipationEnd": {
    "bank": "core",
    "start": 2699868,
    "length": 43629
  },
  "anticipation": {
    "bank": "core",
    "start": 2746143,
    "length": 222264,
    "loopStart": 2751435,
    "loopEnd": 2963115
  },
  "bonusTrigger": {
    "bank": "core",
    "start": 2971053,
    "length": 109678
  },
  "powerStep_1": {
    "bank": "core",
    "start": 3083377,
    "length": 39690
  },
  "powerStep_2": {
    "bank": "core",
    "start": 3125713,
    "length": 39690
  },
  "powerStep_3": {
    "bank": "core",
    "start": 3168049,
    "length": 39690
  },
  "powerStep_4": {
    "bank": "core",
    "start": 3210385,
    "length": 39690
  },
  "powerStep_5": {
    "bank": "core",
    "start": 3252721,
    "length": 39690
  },
  "powerStep_6": {
    "bank": "core",
    "start": 3295057,
    "length": 39690
  },
  "powerStep_7": {
    "bank": "core",
    "start": 3337393,
    "length": 39690
  },
  "powerStep_8": {
    "bank": "core",
    "start": 3379729,
    "length": 39690
  },
  "powerStep_9": {
    "bank": "core",
    "start": 3422065,
    "length": 39690
  },
  "powerStep_10": {
    "bank": "core",
    "start": 3464401,
    "length": 39690
  },
  "powerStep_11": {
    "bank": "core",
    "start": 3506737,
    "length": 39690
  },
  "powerStep_12": {
    "bank": "core",
    "start": 3549073,
    "length": 39690
  },
  "levelUp": {
    "bank": "core",
    "start": 3591409,
    "length": 85785
  },
  "introSting": {
    "bank": "core",
    "start": 3679840,
    "length": 128182
  },
  "playSting": {
    "bank": "core",
    "start": 3810668,
    "length": 76598
  },
  "carouselWhoosh": {
    "bank": "core",
    "start": 3889912,
    "length": 17264
  },
  "coachPop": {
    "bank": "core",
    "start": 3909822,
    "length": 17197
  },
  "flapRattle_0": {
    "bank": "core",
    "start": 3929665,
    "length": 14488
  },
  "flapRattle_1": {
    "bank": "core",
    "start": 3946799,
    "length": 14194
  },
  "flapRattle_2": {
    "bank": "core",
    "start": 3963639,
    "length": 16329
  },
  "flapRattle_3": {
    "bank": "core",
    "start": 3982614,
    "length": 13892
  },
  "flapSettle_0": {
    "bank": "core",
    "start": 3999152,
    "length": 7497
  },
  "flapSettle_1": {
    "bank": "core",
    "start": 4009295,
    "length": 7497
  },
  "flapSettle_2": {
    "bank": "core",
    "start": 4019438,
    "length": 7497
  },
  "trainStep_0": {
    "bank": "core",
    "start": 4029581,
    "length": 8746
  },
  "trainStep_1": {
    "bank": "core",
    "start": 4040973,
    "length": 8781
  },
  "trainStep_2": {
    "bank": "core",
    "start": 4052400,
    "length": 8778
  },
  "signalSwitch": {
    "bank": "core",
    "start": 4063824,
    "length": 35280
  },
  "securityAlarm": {
    "bank": "core",
    "start": 4101750,
    "length": 43897
  },
  "allClear": {
    "bank": "core",
    "start": 4148293,
    "length": 36909
  },
  "incident": {
    "bank": "core",
    "start": 4187848,
    "length": 42611
  },
  "crashRumble": {
    "bank": "core",
    "start": 4233105,
    "length": 30842
  },
  "crashImpact": {
    "bank": "core",
    "start": 4266593,
    "length": 66222
  },
  "wreckScatter": {
    "bank": "core",
    "start": 4335461,
    "length": 41774
  },
  "crashMult": {
    "bank": "core",
    "start": 4379881,
    "length": 25064
  },
  "routeTrace": {
    "bank": "core",
    "start": 4407591,
    "length": 26458
  },
  "bonusIntro": {
    "bank": "extra",
    "start": 2205,
    "length": 129807
  },
  "bonusEnd": {
    "bank": "extra",
    "start": 134658,
    "length": 148643
  },
  "retrigger": {
    "bank": "extra",
    "start": 285947,
    "length": 85865
  },
  "goldenArrive": {
    "bank": "extra",
    "start": 374458,
    "length": 147971
  },
  "bigWinStart": {
    "bank": "extra",
    "start": 525075,
    "length": 127757
  },
  "bigWinTier_0": {
    "bank": "extra",
    "start": 655478,
    "length": 95955
  },
  "bigWinTier_1": {
    "bank": "extra",
    "start": 754079,
    "length": 95835
  },
  "bigWinTier_2": {
    "bank": "extra",
    "start": 852560,
    "length": 94828
  },
  "bigWinTier_3": {
    "bank": "extra",
    "start": 950034,
    "length": 96212
  },
  "bigWinEnd": {
    "bank": "extra",
    "start": 1048892,
    "length": 151230
  },
  "maxWin": {
    "bank": "extra",
    "start": 1202768,
    "length": 214043
  },
  "tierSlam": {
    "bank": "extra",
    "start": 1419457,
    "length": 83389
  }
};

export const VARIANTS: Record<string, VariantInfo> = {
  "uiClick": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiClick"
    ]
  },
  "uiToggle": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiToggle"
    ]
  },
  "uiOpen": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiOpen"
    ]
  },
  "uiClose": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "uiClose"
    ]
  },
  "betUp": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "betUp"
    ]
  },
  "betDown": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "betDown"
    ]
  },
  "spinPress": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "spinPress"
    ]
  },
  "buy": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "buy"
    ]
  },
  "error": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "error"
    ]
  },
  "iris": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "iris"
    ]
  },
  "boostOn": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "boostOn"
    ]
  },
  "boostOff": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "boostOff"
    ]
  },
  "lowPowerClick": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "lowPowerClick"
    ]
  },
  "reelDrop": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3,
      4,
      5
    ],
    "ids": [
      "reelDrop_0",
      "reelDrop_1",
      "reelDrop_2",
      "reelDrop_3",
      "reelDrop_4",
      "reelDrop_5"
    ]
  },
  "reelStop": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "reelStop"
    ]
  },
  "ticketLand": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5,
      6
    ],
    "ids": [
      "ticketLand_1",
      "ticketLand_2",
      "ticketLand_3",
      "ticketLand_4",
      "ticketLand_5",
      "ticketLand_6"
    ]
  },
  "coinLand": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3
    ],
    "ids": [
      "coinLand_0",
      "coinLand_1",
      "coinLand_2",
      "coinLand_3"
    ]
  },
  "locoLand": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "locoLand"
    ]
  },
  "switchLand": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "switchLand"
    ]
  },
  "wildLand": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "wildLand_0",
      "wildLand_1",
      "wildLand_2"
    ]
  },
  "win": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "win"
    ]
  },
  "clusterTrace": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "clusterTrace"
    ]
  },
  "symPretzel": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symPretzel"
    ]
  },
  "symCoffee": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symCoffee"
    ]
  },
  "symNewspaper": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symNewspaper"
    ]
  },
  "symUmbrella": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symUmbrella"
    ]
  },
  "symPigeon": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symPigeon"
    ]
  },
  "symCat": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symCat"
    ]
  },
  "symBulldog": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symBulldog"
    ]
  },
  "symRat": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symRat"
    ]
  },
  "symConductor": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "symConductor"
    ]
  },
  "whistle": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "whistle"
    ]
  },
  "trainDepart": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "trainDepart"
    ]
  },
  "trainRun": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "trainRun"
    ]
  },
  "trainExit": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "trainExit"
    ]
  },
  "trainBrake": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "trainBrake"
    ]
  },
  "coinCollect": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12
    ],
    "ids": [
      "coinCollect_1",
      "coinCollect_2",
      "coinCollect_3",
      "coinCollect_4",
      "coinCollect_5",
      "coinCollect_6",
      "coinCollect_7",
      "coinCollect_8",
      "coinCollect_9",
      "coinCollect_10",
      "coinCollect_11",
      "coinCollect_12"
    ]
  },
  "switchThrow": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "switchThrow"
    ]
  },
  "branch": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "branch"
    ]
  },
  "haulCount": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "haulCount_0",
      "haulCount_1",
      "haulCount_2"
    ]
  },
  "haulMult": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "haulMult"
    ]
  },
  "barTick": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "barTick_0",
      "barTick_1",
      "barTick_2"
    ]
  },
  "barApply": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "barApply"
    ]
  },
  "anticipationStart": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "anticipationStart"
    ]
  },
  "anticipationEnd": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "anticipationEnd"
    ]
  },
  "anticipation": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "anticipation"
    ]
  },
  "bonusTrigger": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bonusTrigger"
    ]
  },
  "powerStep": {
    "base": 1,
    "nums": [
      1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12
    ],
    "ids": [
      "powerStep_1",
      "powerStep_2",
      "powerStep_3",
      "powerStep_4",
      "powerStep_5",
      "powerStep_6",
      "powerStep_7",
      "powerStep_8",
      "powerStep_9",
      "powerStep_10",
      "powerStep_11",
      "powerStep_12"
    ]
  },
  "levelUp": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "levelUp"
    ]
  },
  "introSting": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "introSting"
    ]
  },
  "playSting": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "playSting"
    ]
  },
  "carouselWhoosh": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "carouselWhoosh"
    ]
  },
  "coachPop": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "coachPop"
    ]
  },
  "flapRattle": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3
    ],
    "ids": [
      "flapRattle_0",
      "flapRattle_1",
      "flapRattle_2",
      "flapRattle_3"
    ]
  },
  "flapSettle": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "flapSettle_0",
      "flapSettle_1",
      "flapSettle_2"
    ]
  },
  "trainStep": {
    "base": 0,
    "nums": [
      0,
      1,
      2
    ],
    "ids": [
      "trainStep_0",
      "trainStep_1",
      "trainStep_2"
    ]
  },
  "signalSwitch": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "signalSwitch"
    ]
  },
  "securityAlarm": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "securityAlarm"
    ]
  },
  "allClear": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "allClear"
    ]
  },
  "incident": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "incident"
    ]
  },
  "crashRumble": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "crashRumble"
    ]
  },
  "crashImpact": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "crashImpact"
    ]
  },
  "wreckScatter": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "wreckScatter"
    ]
  },
  "crashMult": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "crashMult"
    ]
  },
  "routeTrace": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "routeTrace"
    ]
  },
  "bonusIntro": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bonusIntro"
    ]
  },
  "bonusEnd": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bonusEnd"
    ]
  },
  "retrigger": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "retrigger"
    ]
  },
  "goldenArrive": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "goldenArrive"
    ]
  },
  "bigWinStart": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bigWinStart"
    ]
  },
  "bigWinTier": {
    "base": 0,
    "nums": [
      0,
      1,
      2,
      3
    ],
    "ids": [
      "bigWinTier_0",
      "bigWinTier_1",
      "bigWinTier_2",
      "bigWinTier_3"
    ]
  },
  "bigWinEnd": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "bigWinEnd"
    ]
  },
  "maxWin": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "maxWin"
    ]
  },
  "tierSlam": {
    "base": 0,
    "nums": [
      0
    ],
    "ids": [
      "tierSlam"
    ]
  }
};

export const TRACKS: Record<string, TrackInfo> = {
  "base": {
    "file": "music-base.mp3",
    "samples": 2374050,
    "loopStart": 11025,
    "loopEnd": 2363025,
    "bpm": 144,
    "beatsPerBar": 4,
    "bars": 32,
    "stems": {}
  },
  "rush": {
    "file": "music-rush.mp3",
    "samples": 1715490,
    "loopStart": 11025,
    "loopEnd": 1704465,
    "bpm": 200,
    "beatsPerBar": 4,
    "bars": 32,
    "stems": {
      "tension": "music-rush-tension.mp3"
    }
  },
  "last": {
    "file": "music-last.mp3",
    "samples": 2138850,
    "loopStart": 11025,
    "loopEnd": 2127825,
    "bpm": 120,
    "beatsPerBar": 4,
    "bars": 24,
    "stems": {}
  },
  "bigwin": {
    "file": "music-bigwin.mp3",
    "samples": 727650,
    "loopStart": 11025,
    "loopEnd": 716625,
    "bpm": 180,
    "beatsPerBar": 4,
    "bars": 12,
    "stems": {}
  },
  "surge": {
    "file": "music-surge.mp3",
    "samples": 586530,
    "loopStart": 11025,
    "loopEnd": 575505,
    "bpm": 150,
    "beatsPerBar": 4,
    "bars": 8,
    "stems": {}
  }
};
